GET http://localhost:3000
Content-Type: application/json

###
POST http://localhost:3000/v1/contacts-macapa
Content-Type: application/json

{
  "contacts": [
    {
      "name": "MARINA RODRIGUES",
      "cellphone": "5541996941911"
    },
    {
      "name": "NICOLAS RODRIGUES",
      "cellphone": "5541954122721"
    }
  ]
}

###

GET http://localhost:3000/v1/contacts-macapa
Content-Type: application/json