version: '3'

services:
  mysql:
    image: mysql
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_HOST=localhost
    ports:
      - "3306:3306"
    container_name: 'mysql'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    container_name: 'postgresql'
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"

volumes:
  postgresql-data:
  mysql-data: