version: '3'

services:
  mysql:
    image: mysql
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin
    ports:
      - '3306:3306'
    container_name: 'mysql'
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-compose-network

  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    container_name: 'postgresql'
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    networks:
      - postgres-compose-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql
      - mysql
    networks:
      - postgres-compose-network
      - mysql-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
  mysql-compose-network:
    driver: bridge

volumes:
  postgresql-data:
  mysql-data: