export enum ErrorsCode {
  FAIL_TO_CREATE_MACAPA_CONTACTS = 'FAIL_TO_CREATE_MACAPA_CONTACTS',
  FAIL_TO_FIND_ALL_MACAPA_CONTACTS = 'FAIL_TO_FIND_ALL_MACAPA_CONTACTS',
  FAIL_TO_CREATE_VAREJAO_CONTACTS = 'FAIL_TO_CREATE_VAREJAO_CONTACTS',
  FAIL_TO_FIND_ALL_VAREJAO_CONTACTS = 'FAIL_TO_FIND_ALL_VAREJAO_CONTACTS',
}
